### ISSUE TITLE
Visualization of attention layer

### ISSUE THREAD

**Issue by wanmeiziyoulan** [ethancaballero/Improved-Dynamic-Memory-Networks-DMN-plus#6]
Hi,
  The paper provide the comparison of original images and attention images, How to obtain visualization of attention layer? Could you please share some code about it?
  Thanks.

**Comment by ethancaballero** [comment]
"attentions": np.array([ret[2]]) returns how much each sentence is attended to:
https://github.com/ethancaballero/Improved-Dynamic-Memory-Networks-DMN-plus/blob/master/dmn_tied.py#L642
https://github.com/ethancaballero/Improved-Dynamic-Memory-Networks-DMN-plus/blob/master/dmn_untied.py#L646
